#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# RERO ID
# Copyright (C) 2020 RERO.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>

set -e

# Clean redis
pipenv run invenio shell --no-term-title -c "import redis; redis.StrictRedis.from_url(app.config['CACHE_REDIS_URL']).flushall(); print('Cache cleared')"
pipenv run invenio db destroy --yes-i-know
pipenv run invenio db init create

# Create admin role to restrict access
pipenv run invenio roles create admin
pipenv run invenio access allow superuser-access role admin
pipenv run invenio users create -a --password administrator admin@rero.ch
pipenv run invenio roles add admin@rero.ch admin
pipenv run invenio apps create admin@rero.ch rero-ils https://ils.rero.ch -r "https://ils.rero.ch/oauth/authorized/reroid/" -r "https://ils.test.rero.ch/oauth/authorized/reroid/"  -r "https://ilsdev.test.rero.ch/oauth/authorized/reroid/" -r "https://localhost:5000/oauth/authorized/reroid/" -d "Integrated Library System flavour of Invenio by RERO." -i ${REROILS_CLIENT_ID:-""} -s ${REROILS_CLIENT_SECRET:-""}
pipenv run invenio apps create admin@rero.ch sonar https://sonar.ch -r "https://sonar.ch/oauth/authorized/reroid/"  -r "https://sonar.test.rero.ch/oauth/authorized/reroid/"  -r "https://sonardev.test.rero.ch/oauth/authorized/reroid/" -r "https://localhost:5000/oauth/authorized/reroid/" -d "Swiss Open Access Repository." -i ${SONAR_CLIENT_ID:-""} -s ${SONAR_CLIENT_SECRET:-""}
